name: Deploy Databricks Job

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    defaults:
      run:
        working-directory: apps/dev

    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug working directory
        run: |
          echo "PWD inside apps/dev:"
          pwd
          echo "Listing files in current dir:"
          ls -la
          echo "Going one level up to verify root layout:"
          ls -la ../..

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve -var="notebook_file_path=../../notebooks/nightly_sku_alert_job.py"
